eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000

config:
  security:
    oauth:
      client:
        secret: '12345'
        id: frontendapp
      jwt:
        key: algun_codigo_secreto_aeiou

management:
  endpoints:
    web:
      exposure:
        include: '*'