server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  routes:
    gdmt-identitymanagement-neg-develop:
      service-id: gdmt-identitymanagement-neg-develop
      path: /gdmt-identitymanagement-neg-develop/**

    gdmt-retentionschedules-neg-develop:
      service-id: gdmt-retentionschedules-neg-develop
      path: /gdmt-retentionschedules-neg-develop/**

    gdmt-logicalfolders-neg:
      service-id: gdmt-logicalfolders-neg
      path: /document-management/logical-folders/**

    file:
      service-id: microservice-file
      path: /api-files/**

    documents:
      service-id: microservice-document
      path: /api-documents/**

    oauth2:
      service-id: microservice-oauth2
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie