server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    url: ${ms.datasource.url}
    username: ${ms.datasource.username}
    password: ${ms.datasource.password}
  flyway:
    enabled: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://gdmt-ms-zipkin-server:9411

application:
  identityTypeGroup: GROUP
  identityTypeUser: USER
  errors:
    cross:
      userNotFound:
        code: GDMT_IMN_000
        message: User not found.
    createUser:
      userAlreadyExists:
        code: GDMT_IMN_001
        message: User already exists.
      roleNotFound:
        code: GDMT_IMN_002
        message: Role not found.
      emailAlreadyExists:
        code: GDMT_IMN_008
        message: Email already associated with another user.
    changeUserPassword:
      previousPasswordIncorrect:
        code: GDMT_IMN_003
        message: Previous password is incorrect.
      newPasswordEqualsOldPassword:
        code: GDMT_IMN_004
        message: New password is the same as the old password.
    createGroup:
      groupAlreadyExists:
        code: GDMT_IMN_005
        message: Group already exists.
      groupNotFound:
        code: GDMT_IMN_006
        message: Group not found.
    setUpGroupPermission:
      groupPermissionNotFound:
        code: GDMT_IMN_007
        message: Group permission %s not found.
  globalResourceTypes:
    - USER
    - GROUP
    - DOCUMENT_TYPE
    - DOCUMENTARY_AREA