server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  routes:
    gdmt-identitymanagement-neg:
      service-id: gdmt-identitymanagement-neg
      path: /gdmt-identitymanagement-neg/**

    gdmt-retentionschedules-neg:
      service-id: gdmt-retentionschedules-neg
      path: /gdmt-retentionschedules-neg/**

    gdmt-logicalfolders-neg:
      service-id: gdmt-logicalfolders-neg
      path: /document-management/logical-folders/**

    file:
      service-id: microservice-file
      path: /api-files/**

    documents:
      service-id: microservice-document
      path: /api-documents/**

    gdmt-oauth2-server-develop:
      service-id: gdmt-oauth2-server-develop
      sensitive-headers: Cookie,Set-Cookie
      path: /document-management/gdmt-oauth2-server-develop/**