server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  routes:
    gdmt-identitymanagement-neg:
      service-id: gdmt-identitymanagement-neg
      path: /gdmt-identitymanagement-neg/**

    gdmt-retentionschedules-neg:
      service-id: gdmt-retentionschedules-neg
      path: /gdmt-retentionschedules-neg/**

    gdmt-oauth2-server:
      service-id: gdmt-oauth2-server
      path: /gdmt-oauth2-server/**
      sensitive-headers: Cookie,Set-Cookie