server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://gdmt-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  routes:
    gdmt-identitymanagement-neg:
      service-id: gdmt-identitymanagement-neg
      path: /gdmt-identitymanagement-neg/**

    gdmt-logicalfolders-neg:
      service-id: gdmt-logicalfolders-neg
      path: /gdmt-logicalfolders-neg/**

    gdmt-retentionschedules-neg:
      service-id: gdmt-retentionschedules-neg
      path: /gdmt-retentionschedules-neg/**

    gdmt-oauth2-server:
      service-id: gdmt-oauth2-server
      path: /gdmt-oauth2-server/**
      sensitive-headers: Cookie,Set-Cookie